/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-env.d.ts` (hash: 816402ff7ea0213e4026645ea28a0443)
interface __BaseEnv_Env {
	ARCADE_DB: D1Database;
	ARCADE_RECEIPT_TOKEN?: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./server");
	}
	interface LandingEnv {
		ARCADE_DB: D1Database;
	ARCADE_RECEIPT_TOKEN?: string;
	}
	interface AppEnv {
		ARCADE_DB: D1Database;
	ARCADE_RECEIPT_TOKEN?: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
